import Foundation
import SwiftData

@Model
final class WorkoutTemplate {
    var id: UUID = UUID()
    var name: String = ""
    var createdAt: Date = Date()
    var lastUsedAt: Date = Date()
    var isFavorite: Bool = false
    /// True for templates generated by materialising a multi-week program (see
    /// `ProgramMaterializer`). These are an implementation detail of the program —
    /// there is one per session×block — so they're hidden from the user's browsable
    /// template lists, while the schedule rows that reference them work normally.
    /// Additive with a default → lightweight, CloudKit-compatible migration.
    var isProgramGenerated: Bool = false
    /// The `RecommendedWorkout.id` this plan was materialised from, when the user
    /// scheduled a prebuilt workout. Lets us reuse one template per prebuilt instead
    /// of duplicating it each time it's scheduled. nil for hand-built plans.
    var recommendedSourceID: String?
    /// The timer settings (durations, rounds, interval work/rest, rest between sets)
    /// this plan uses, JSON-encoded via `TimerConfig`. Persisted so a saved or
    /// scheduled workout opens with its exact timings instead of defaults. nil for
    /// plans saved before this field existed. Additive → lightweight migration.
    var timerConfigData: Data?

    @Relationship(deleteRule: .cascade, inverse: \TemplateExercise.template)
    var exercises: [TemplateExercise] = []

    @Relationship(deleteRule: .nullify, inverse: \WorkoutSchedule.template)
    var schedules: [WorkoutSchedule] = []

    init(
        id: UUID = UUID(),
        name: String,
        createdAt: Date = Date(),
        lastUsedAt: Date = Date()
    ) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.lastUsedAt = lastUsedAt
        self.exercises = []
        self.schedules = []
    }

    var sortedExercises: [TemplateExercise] {
        exercises.sorted { $0.sortOrder < $1.sortOrder }
    }

    /// The timer configuration this plan was saved with, decoded from
    /// `timerConfigData`. nil for legacy plans saved before it was recorded.
    var storedConfig: TimerConfig? {
        get {
            guard let data = timerConfigData else { return nil }
            return try? JSONDecoder().decode(TimerConfig.self, from: data)
        }
        set { timerConfigData = newValue.flatMap { try? JSONEncoder().encode($0) } }
    }
}

@Model
final class TemplateExercise {
    var id: UUID = UUID()
    var timerTypeRaw: String = TimerType.reps.rawValue
    var timerConfigData: Data?
    var targetSets: Int = 3
    var targetReps: Int = 10
    /// Hold time in seconds for timed exercises (e.g. planks). 0 = rep-based.
    var targetDuration: Int = 0
    var sortOrder: Int = 0
    var exerciseName: String = ""
    var equipmentRaw: String?
    var targetWeight: Double = 0
    var weightUnitRaw: String = WeightUnit.lb.rawValue
    /// Reps: rest between sets in seconds for this exercise. 0 = fall back to
    /// the workout default (seeded from Settings).
    var restSeconds: Int = 0
    /// Supersetted with the next exercise in the template.
    var linkedToNext: Bool = false
    /// AMRAP: a new timed round starts after this exercise.
    var roundBreakAfter: Bool = false
    /// AMRAP: duration in minutes of the round this exercise starts
    /// (0 = not set; only meaningful on the first exercise of a round).
    var roundMinutes: Int = 0

    var template: WorkoutTemplate?

    init(
        id: UUID = UUID(),
        exerciseName: String,
        timerType: TimerType = .reps,
        targetSets: Int = 3,
        targetReps: Int = 10,
        targetDuration: Int = 0,
        sortOrder: Int = 0,
        equipment: Equipment? = nil,
        targetWeight: Double = 0,
        weightUnit: WeightUnit = .lb,
        linkedToNext: Bool = false
    ) {
        self.id = id
        self.exerciseName = exerciseName
        self.timerTypeRaw = timerType.rawValue
        self.targetSets = targetSets
        self.targetReps = targetReps
        self.targetDuration = targetDuration
        self.sortOrder = sortOrder
        self.equipmentRaw = equipment?.rawValue
        self.targetWeight = targetWeight
        self.weightUnitRaw = weightUnit.rawValue
        self.linkedToNext = linkedToNext
    }

    var timerType: TimerType {
        TimerType(rawValue: timerTypeRaw) ?? .reps
    }

    var equipment: Equipment? {
        guard let e = equipmentRaw else { return nil }
        return Equipment(rawValue: e)
    }

    var weightUnit: WeightUnit {
        WeightUnit(rawValue: weightUnitRaw) ?? .lb
    }
}
